### ISSUE TITLE
[MIUI] PDFs exported from GoodNotes display handwritten lines incorrectly in some cases

### ISSUE THREAD

**Issue by Lopolin-LP** [mudlej/mj_pdf#2] opened 2023-02-28 11:13 UTC
The title speaks for itself. I’ll provide some screenshots below.

On my School iPad, Built-In PDF Viewer:
![116E4596-D61E-4816-BFAC-034B852EAC20](https://user-images.githubusercontent.com/82715586/221829752-d51b0dfc-5ef5-442e-bad4-055cea5be882.jpeg)

On My Android Smartphone, MJ PDF Version 2.0.1:
![445AE3BC-B1BA-4A74-92EB-1DF0E951733E](https://user-images.githubusercontent.com/82715586/221829883-a3860248-7799-4880-95ad-a1ddb24e4843.jpeg)

Original File (PDF): [Untitled (Draft).pdf](https://github.com/mudlej/mj_pdf/files/10849488/Untitled.Draft.pdf)
Original File (Goodnotes; hosted on Mediafire): [Untitled (Draft) 2.goodnotes](https://www.mediafire.com/file/847tzzvlmqu2lzn/Untitled+(Draft)+2.goodnotes/file)

From these Screenshots you can see already a few Problems:
- The first „i“-Dot
- The lowercase „t“ in the first Row being longer and sharply cut-off
- The Word „Rendering“
	- Both the „R“ and „d“ are getting screwed over like the first „i“-Dot
- The „-“ in „Line-Rendering“
- Depending on zoom Level (example. 10x) the Shape changes
- This is using default settings, but doesn’t change regardless of settings.
- In larger GoodNotes PDFs this just escalates and is everywhere you look

This may have to do something on how vectors are being rendered within MJ PDF or one of it’s components, but I’m not so sure.

I do not have this issue with MuPDF, KOReader and LibreraPDF. Afaik only one other PDF Reader I tried had the exact same issue, but I do not recall which one it was.

**Comment by mudlej** [comment] 2023-02-28 17:14
I couldn't reproduce the behavior. I tried with several phones.
![image](https://user-images.githubusercontent.com/110748150/221927487-9d5be0b8-5054-4376-a580-cca375077221.png)

**Comment by Lopolin-LP** [comment] 2023-02-28 22:46
That makes it even weirder. I have a POCO X3 Pro with MIUI 12.5.5, I don't know if that's Relevant here though. The same issue seems to appear within Xiaomis own Mi Documents Viewer too, which is based(?) on WPS Office, which (surprise) has also this issue. I uninstalled Xiaomi's Document Viewer now.

**Comment by Lopolin-LP** [comment] 2023-02-28 23:00
On the official Goodnotes Support Website it seems to be a known issue. https://support.goodnotes.com/hc/en-us/articles/360002125435-My-exported-PDF-shows-spikes-or-smearing-in-some-of-the-strokes-in-a-PDF-viewer

Yet this still doesn't explain why you don't have any Problems. Whatever, I'll try it on an Emulator tomorrow just because I can.

**Comment by mudlej** [comment] 2023-03-01 17:29
Xiaomi again! 
I think you are the 5th or 6th person to report issues on Xiaomi devices!
And all of them were using the official rom. The people who used a custom rom didn't report any problems.

**Comment by Lopolin-LP** [comment] 2023-03-01 18:15
oh my god, first I lose (almost) everything on my phone because **_it_** forgot it's password pattern somehow and now this.
Well this just pushes me further to buy a new phone next year... and yes, I have the official ROM.

Anyways the issue also happens on Bluestacks 5 (using any Android Version), so you could try that if you really want to fix this.

**Comment by mudlej** [comment] 2023-08-03 03:45
There is nothing to be done about this issue.
So, I am closing it.

**Closed by mudlej** 2023-08-03 03:45 UTC
